dataset_name: SCADA_yolo
model_path: models/weights/best_GridAnchor.pth
input_size: 608
mAP_iou_threshold: 0.5
lambda_obj: 20.0
lambda_noobj: 1.0
lambda_lct_loss: 10.0
lambda_conf_loss: 2.0
lambda_cls_loss: 1.0
gamma: 1.5
alpha: 0.75
cls_alpha: 3.0
batch_size: 8
learning_rate: 0.001
cls_list: [RD, RS, GD, GS, RDL, RSL, GDL, GSL, Text]
nc: 9
anchors:
- [0.0616, 0.0361]
- [0.0211, 0.0376]
- [0.0256, 0.0453]
- [0.0172, 0.0303]
- [0.0561, 0.0363]
