dataset_name: SCADA_yolo
input_size: 608
mAP_iou_threshold: 0.5
lambda_obj: 20.0
lambda_noobj: 1.0
lambda_lct_loss: 10.0
lambda_conf_loss: 2.0
lambda_cls_loss: 1.0
gamma: 1.5
alpha: 0.75
cls_alpha: 3.0
batch_size: 8
learning_rate: 0.001
cls_list: [RD, RS, GD, GS, RDL, RSL, GDL, GSL, Text]
nc: 9
anchors:
- [0.0172, 0.0302]
- [0.0617, 0.0361]
- [0.0255, 0.0456]
- [0.0212, 0.0376]
- [0.0564, 0.036]
